package sidly.wynnadhoc.wapi.item.enums;

public enum Emblem {
    SHIELD_3, SHIELD, SHIELD_2, SHIELD_5, STICKER_6, SHIELD_4, STICKER_5, DIAMOND_2,
    STICKER_4, DIAMOND_1, SHIELD_1, STICKER_3, STICKER_2, DIAMOND_6, SQUARE_4, DIAMOND_5,
    SQUARE_5, DIAMOND_4, DIAMOND_3, SQUARE_6, SQUARE, STICKER_1, SHIELD_6
}
