package sidly.wynnadhoc.wapi.item.enums;

public enum SubType {
    SCYTHE, RING, PICKAXE, ROD, BOW, RELIK, AXE, SPEAR, ARMOUR_TOME, HELMET, FARMING,
    BOOTS, LEGGINGS, DAGGER, WEAPON_TOME, EXPERTISE_TOME, MARATHON_TOME, FISHING,
    NECKLACE, BRACELET, MINING, MYSTICISM_TOME, WOODCUTTING, CHESTPLATE, LOOTRUN_TOME,
    WAND, GUILD_TOME
}
